//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claim.ClaimService.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserRole
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AppRoleId { get; set; }
    
        public virtual AppRole AppRole { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
