//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claim.ClaimService.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public System.Guid ClaimId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfAccident { get; set; }
        public string PatientGender { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ClaimStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
